using System.Collections;
using System.Collections.Generic;


public class Codes  {
    public static string[] codes = {
"Malefian Essence",
"Sweat Bun",
"Porridge",
"Pie",
"Sugar",
"Elven Wine",
"Green Elfcress",
"Fairy Dust",
"Fiber",
"Stagswift Wine",
"Steak",
"Daffodil Seed",
"Cooking Herbs",
"Bone Shards",
"Bread",
"Beast and Cabbage",
"Broth",
"Blazepitch",
"Bottle of Orange Ink",
"Bottle of Green Ink",
"Blazepitch",
"Cooking Herbs",
"Sandwich",
"Cider",
"Haggis",
"Apple",
"Hearty Stew",
"Dwarven Stout",
"Grain",
"Broth",
"Stagswift Wine",
"Thistle Seed",
"Hearty Stew",
"Roasted Carrot",
"Hellebore Seed",
"Cider",
"Blue Witchroot",
"Wood",
"Tea",
"lily Seed",
"Keg",
"Onion",
"Potato",
"Tropical Drink",
"Charcoal",
"Malefian Essence",
"Daffodil Seed",
"Shepherds Pie",
"Bone Shards",
"Fiber",
"Blessed Wafer",
"Red Colewort",
"Selkie's Tears",
"Carrot",
"Lily Seed",
"Deathcap Mushrooms",
"Fermented Spiirit",
"Baked Potato",
"Meat",
"Bluebell Seed",
"Soup",
"Metal Scraps",
"Beast and Cabbage",
"Pie",
"Thistle Seed",
"Bread",
"Mushrooms",
"Gold Trefoil",
"Cabbage",
"Baked Potato",
"Steak",
"Roast Beast",
"Porridge",
"Dwarven Stout",
"Tropical Drink",
"Haggis",
"Selkie's Tears",
"Keg",
"Meat",
"Wrecker's Dram",
"Fairy Dust",
"Wood",
"Roasted Carrot",
"Rotted Food",
"Sweet Bun",
"Sandwich",
"Roast Beast",
"Fermented Spirit",
"Shepherds Pie",
"Hellebore Seed",
"Metal Scraps",
"Bluebell Seed",
"Water",
"Tea",
"Soup",
"Blessed Wafer" };
}
